version: '2.1'
services:

    postgres:
        image: fetchq/fetchq:10.4-1.3.0
        ports:
            - ${PG_PORT:-5432}:5432
        environment:
            POSTGRES_USER: ${PG_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
            POSTGRES_DB: ${PG_DATABASE:-postgres}
        volumes:
            - ${HUMBLE_DATA}/pg-dev:/var/lib/postgresql/data
            - ${HUMBLE_BACKUP}/pg-dev/backup:/backup
        restart: always

    elasticsearch:
        image: elasticsearch:7.2.0
        ports:
            - ${ELASTICSEARCH_PORT:-9200}:9200
        environment:
            - discovery.type=single-node
            # - discovery.seed_hosts=es02
            # - cluster.initial_master_nodes=es01,es02
            # - cluster.name=docker-cluster
            # - bootstrap.memory_lock=true
            # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        # ulimits:
        #     memlock:
        #       soft: -1
        #       hard: -1
        volumes:
            - ${HUMBLE_DATA}/elasticsearch:/usr/share/elasticsearch/data

    kibana:
        image: kibana:7.2.0
        ports:
            - ${KIBANA_PORT:-5601}:5601
        environment:
            ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOST:-http://elasticsearch:9200}
        # volumes:
        #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml

    mongo:
        image: mongo:3.4
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin}
        restart: always

    mongo-express:
        image: mongo-express:0.49
        ports:
            - ${MONGO_EXPRESS_PORT:-8081}:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USERNAME:-admin}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin}
        restart: always

    grafana:
        image: grafana/grafana:5.0.4
        ports:
            - ${GRAFANA_PORT-5555}:3000
        environment:
            GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
        volumes:
            - ${HUMBLE_DATA}/grafana:/var/lib/grafana

    redis:
        image: redis:5.0.5
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - ${REDIS_PORT-6379}:6379
        volumes:
            - ${HUMBLE_DATA}/redis:/var/lib/redis
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        restart: always

    webapp:
        image: node:12.2-alpine
        # ports:
        #     - ${WEBAPP_API_PORT:-8080}:8080
        #     - ${WEBAPP_CRA_PORT:-3000}:3000
        # volumes:
        #     # - ${HUMBLE_DATA}/webapp/node_modules:/usr/src/app/node_modules:cached
        #     # - ${HUMBLE_DATA}/webapp/node_build:/usr/src/app/node_build:cached
        #     - ./services/webapp/package.json:/usr/src/app/package.json:delegated
        #     - ./services/webapp/yarn.lock:/usr/src/app/yarn.lock:delegated
        #     - ./services/webapp/jsconfig.json:/usr/src/app/jsconfig.json:delegated
        #     - ./services/webapp/src:/usr/src/app/src:delegated
        #     - ./services/webapp/ssr:/usr/src/app/ssr:delegated
        #     - ./services/webapp/public:/usr/src/app/public:delegated
        #     - ./services/webapp/index.js:/usr/src/app/index.js:delegated
        #     - ./services/webapp/.env:/usr/src/app/.env:delegated
        # environment:
        #     NODE_ENV: development
        #     PG_HOST: ${PG_HOST:-postgres}
        #     PG_PORT: ${PG_PORT:-5432}
        #     PG_USERNAME: ${PG_USERNAME:-postgres}
        #     PG_PASSWORD: ${PG_PASSWORD:-postgres}
        #     PG_DATABASE: ${PG_DATABASE:-postgres}
        #     JWT_SECRET: ${JWT_SECRET:-grapi}
        #     JWT_DURATION: ${JWT_DURATION:-1y}
        #     BCRYPT_ROUNDS: ${BCRYPT_ROUNDS:-5}
        # working_dir: /usr/src/app
        # entrypoint: [ "yarn", "start:dev" ]
