
refresh:
	cp ../shared-node/.env ./.env
	cp ../shared-node/package.json ./package.json
	cp ../shared-node/index.js ./index.js
	cp ../shared-node/.gitignore ./.gitignore
	cp ../shared-node/Dockerfile ./Dockerfile

	cp ../shared-node/src/boot.js ./src/boot.js
	cp -a ../shared-node/src/services ./src/
