version: '3.1'

services:

  postgres:
    image: postgres:11.4
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: passenger
        POSTGRES_PASSWORD: passenger
        POSTGRES_DB: passenger
    volumes:
        - ${HUMBLE_DATA}/pg:/var/lib/postgresql/data
        - ${HUMBLE_BACKUP}:/backup
    restart: always

  mongo:
    image: mongo:3.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always

  mongo-express:
    image: mongo-express:0.49
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    restart: always
