version: '3.4'
services:
    workers:
        build: .
        environment:
            NODE_ENV: production
            LOG_LEVEL: ${LOG_LEVEL}
            PG_HOST: ${PG_HOST}
            PG_PORT: ${PG_PORT}
            PG_PASSWORD: ${PG_PASSWORD}
            PG_DATABASE: ${PG_DATABASE}
            PG_USERNAME: ${PG_USERNAME}
            API_ENDPOINT: ${API_ENDPOINT}
            API_TOKEN: ${API_TOKEN}
