version: '3.4'
services:
    app:
        build: .
        ports:
            - ${PORT:-8080}:8080
        environment:
            NODE_ENV: production
            PG_HOST: ${PG_HOST}
            PG_PORT: ${PG_PORT}
            PG_PASSWORD: ${PG_PASSWORD}
            PG_DATABASE: ${PG_DATABASE}
            PG_USERNAME: ${PG_USERNAME}

    buildApp:
        image: alialfredji/api-build:0.0.1
        ports:
            - 8081:8080
        environment:
            NODE_ENV: production
            PG_HOST: ${PG_HOST}
            PG_PORT: ${PG_PORT}
            PG_PASSWORD: ${PG_PASSWORD}
            PG_DATABASE: ${PG_DATABASE}
            PG_USERNAME: ${PG_USERNAME}